In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [2]:
#Check missing value proportion
x = df.isnull().sum()
x = x[x>0]
x.sort_values(ascending= False,inplace = True)

x = (x/df.shape[0]) * 100 
x

#Dữ liệu bị thiếu quá nhiều, chúng ta nên xử lý thế nào?

PoolQC          99.520548
MiscFeature     96.301370
Alley           93.767123
Fence           80.753425
FireplaceQu     47.260274
LotFrontage     17.739726
GarageType       5.547945
GarageYrBlt      5.547945
GarageFinish     5.547945
GarageQual       5.547945
GarageCond       5.547945
BsmtExposure     2.602740
BsmtFinType2     2.602740
BsmtFinType1     2.534247
BsmtCond         2.534247
BsmtQual         2.534247
MasVnrArea       0.547945
MasVnrType       0.547945
Electrical       0.068493
dtype: float64

In [3]:
#Impute missing value
df["PoolQC"] = df["PoolQC"].fillna("No Pool")
df["MiscFeature"] = df["MiscFeature"].fillna("No Misc")
df["Alley"] = df["Alley"].fillna("No alley")
df["Fence"] = df["Fence"].fillna("No Fence")
df["FireplaceQu"] = df["FireplaceQu"].fillna("No Fireplace")
df["LotFrontage"] = df.groupby("Neighborhood")["LotFrontage"].transform(lambda x: x.fillna(x.median()))
df["LotFrontage"] = df["LotFrontage"].fillna(df.groupby("Neighborhood")["LotFrontage"].transform("median"))
df["GarageType"] = df["GarageType"].fillna("No Garage")
df["GarageYrBlt"] = df["GarageYrBlt"].fillna(0)
df["GarageFinish"] = df["GarageFinish"].fillna("No Garage")
df["GarageQual"] = df["GarageQual"].fillna("No Garage")
df["GarageCond"] = df["GarageCond"].fillna("No Garage")
df["BsmtExposure"] = df["BsmtExposure"].fillna("No Basement")
df["BsmtFinType2"] = df["BsmtFinType2"].fillna("No Basement")
df["BsmtQual"] = df["BsmtQual"].fillna("No Basement")
df["BsmtCond"] = df["BsmtCond"].fillna("No Basement")
df["BsmtFinType1"] = df["BsmtFinType1"].fillna("No Basement")
df["MasVnrType"] = df["MasVnrType"].fillna("None")
df["MasVnrArea"] = df["MasVnrArea"].fillna(0.0)
df["Electrical"] = df["Electrical"].fillna(df["Electrical"].mode()[0])

In [4]:
#Change numerical columns into categorical.
df["MSSubClass"] = df["MSSubClass"].astype(str)
df["OverallQual"]= df["OverallQual"].astype(str)
df["OverallCond"] = df["OverallCond"].astype(str)
df["YearBuilt"] = df["YearBuilt"].astype(str)
df["YearRemodAdd"] = df["YearRemodAdd"].astype(str)
df["GarageYrBlt"] = df["GarageYrBlt"].astype(str)
df["MoSold"] = df["MoSold"].astype(str)
df["YrSold"] = df["YrSold"].astype(str)

In [9]:
#Encoding categorical variable
from sklearn.preprocessing import LabelEncoder
#In ra những cột mang giá trị định tính
for i in df.select_dtypes(include = "object").columns:
    label_encoder = LabelEncoder()
    df[i] = label_encoder.fit_transform(list(df[i].values))

Onehot Encoding
from sklearn.preprocessing import OneHotEncoder
df = pd.get_dummies(df)
df

#Frequency Encoding
for i in df.select_dtypes(include = "object").columns:
    fe = df.groupby(i).size()/df.shape[0]
    df.loc[:,i + "_Freq_Encoded"] = df[i].map(fe)

df = pd.get_dummies(df)
df

,Id,LotFrontage,LotArea,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,65.0,8450,196.0,706,0,150,856,856,854,...,0,0,0,1,0,0,0,0,1,0
1,2,80.0,9600,0.0,978,0,284,1262,1262,0,...,0,0,0,1,0,0,0,0,1,0
2,3,68.0,11250,162.0,486,0,434,920,920,866,...,0,0,0,1,0,0,0,0,1,0
3,4,60.0,9550,0.0,216,0,540,756,961,756,...,0,0,0,1,1,0,0,0,0,0
4,5,84.0,14260,350.0,655,0,490,1145,1145,1053,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,62.0,7917,0.0,0,0,953,953,953,694,...,0,0,0,1,0,0,0,0,1,0
1456,1457,85.0,13175,119.0,790,163,589,1542,2073,0,...,0,0,0,1,0,0,0,0,1,0
1457,1458,66.0,9042,0.0,275,0,877,1152,1188,1152,...,0,0,0,1,0,0,0,0,1,0
1458,1459,68.0,9717,0.0,49,1029,0,1078,1078,0,...,0,0,0,1,0,0,0,0,1,0
1459,1460,75.0,9937,0.0,830,290,136,1256,1256,0,...,0,0,0,1,0,0,0,0,1,0

In [10]:
df["MSSubClass_Freq_Encoded"]

0       0.204795
1       0.367123
2       0.204795
3       0.041096
4       0.204795
          ...
1455    0.204795
1456    0.367123
1457    0.041096
1458    0.367123
1459    0.367123
Name: MSSubClass_Freq_Encoded, Length: 1460, dtype: float64